// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuh_s3M5H00zlh0LTeix7E79BRrz1-xyA',
    appId: '1:868573271277:web:b8887d1c73236d603ee8e4',
    messagingSenderId: '868573271277',
    projectId: 'fir-2-b724c',
    authDomain: 'fir-2-b724c.firebaseapp.com',
    databaseURL: 'https://fir-2-b724c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-2-b724c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKBwDjMpbeyGWFb6h12bHuxKwMLtWEgZk',
    appId: '1:868573271277:android:dbdbd6dae92b2ece3ee8e4',
    messagingSenderId: '868573271277',
    projectId: 'fir-2-b724c',
    databaseURL: 'https://fir-2-b724c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-2-b724c.appspot.com',
  );
}
